name: Go
on: [push]
jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Create artifacts directory
      run: mkdir -p artifacts

    - name: Tests
      run: go test ./... -json > artifacts/report.json

    - name: Coverage
      run: go test ./... -coverprofile=artifacts/coverage.out

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run --out-format checkstyle > artifacts/golangci-lint-report.out || true

    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Download code coverage results
        uses: actions/download-artifact@v1
        with:
          name: artifacts
          path: artifacts
        
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
